import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Favour Okeke Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-8">
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className="text-xl font-burtons">Welcome!</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-7' href="#">Resume</a></li>
            </ul>
          </nav>
          
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-teal-600 text-medium'>I'm Favour Okeke</h2>
            <h3 className='text-2xl py-2'>Frontend Developer</h3>
            <p className='text-md py-3 leading-8 text-gray-800'>I design and code beautiful interface for exciting user experience.
               I'm very optimistic and always ready to learn.</p>
          </div>

          <div className='text-4xl flex justify-center gap-16 py-2 text-gray-600'>
             <AiFillTwitterCircle />
             <AiFillLinkedin />
             <AiFillGithub />
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 '>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Since the beginning of my journey as a freelance developer,
               I've done remote work for <span className='text-teal-500'>agencies</span> consulted 
               for <span className='text-teal-500'>startups</span> and collaborated with talented people to create digital products
               for both business and consumer use.</p>
            <p className='text-md py-2 leading-8 text-gray-800'>Since the beginning of my journey as a freelance developer,
               I've done remote work for a long time.</p>
          </div>

          <div>
            <div className='grid place-items-center text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100}  />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your 
                needs following core design theory.</p>
              <h4 className='text-teal-600 py-4'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='grid place-items-center text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100}  />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your 
                needs following core design theory.</p>
              <h4 className='text-teal-600 py-4'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='grid place-items-center text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100}  />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your 
                needs following core design theory.</p>
              <h4 className='text-teal-600 py-4'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
