import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Favour Okeke Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-8">
        <section className=' min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className="text-xl font-burtons">Welcome!</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-7' href="#">Resume</a></li>
            </ul>
          </nav>
          
          <div className='text-center p-10'>
            <h2 className='text-4xl py-2 text-teal-600 text-medium'>I'm Favour Okeke</h2>
            <h3 className='text-2xl py-2'>Frontend Developer</h3>
            <p className='text-md py-3 leading-8 text-gray-800'>I design and code beautiful interface for exciting user experience.
               I'm very optimistic and always ready to learn.</p>
          </div>

          <div className='text-4xl flex justify-center gap-16 py-2 text-gray-600'>
             <AiFillTwitterCircle />
             <AiFillLinkedin />
             <AiFillGithub />
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>
      </main>

    </div>
  )
}
